#ifndef GUARD_CONSTANTS_POKEMON_POWDER_JAR_H
#define GUARD_CONSTANTS_POKEMON_POWDER_JAR_H

enum PokemonPowderJarResultCodes
{
    POKEMON_POWDER_JAR_RESULT_FAIL_TYPE_0,
    POKEMON_POWDER_JAR_RESULT_FAIL_TYPE_1,
    POKEMON_POWDER_JAR_RESULT_FAIL_FAINTED,
    POKEMON_POWDER_JAR_RESULT_FAIL_HAS_STATUS,
    POKEMON_POWDER_JAR_RESULT_FAIL_ABILITY,
    POKEMON_POWDER_JAR_RESULT_SUCCESS,
    POKEMON_POWDER_JAR_RESULT_COUNT,
};

#endif // GUARD_CONSTANTS_POKEMON_POWDER_JAR_H